---
title: "Importing data"
author: "Your Name"
format: html
---

## Header 1

```{r setup}
#| include: false
library(tidyverse)
library(here)
source(here("R/functions.R"))
library(fs)
```



```{r}
#| eval: false
here("data-raw/nurses-stress/stress/5C/5C_1586886626/HR.csv.gz") %>%
  read_csv(
    show_col_types = FALSE,
    name_repair = to_snake_case,
    n_max = 100
  )
```

## Exercise: Reading other files


```{r}
#| eval: false
here("data-raw/nurses-stress/stress/5C/5C_1586886712/HR.csv.gz") %>%
  read_csv(
    show_col_types = FALSE,
    name_repair = to_snake_case
  )
```
```{r}
#| eval: false
here("data-raw/nurses-stress/stress/5C/5C_1586886712/HR.csv.gz") %>%
  read_csv(
    show_col_types = FALSE,
    name_repair = to_snake_case,
    n_max = 100
  )
```


```{r}
#| eval: false
here("data-raw/nurses-stress/stress/6B/6B_1587569373/EDA.csv.gz") %>%
  read_csv(
    show_col_types = FALSE,
    name_repair = to_snake_case
  )
```


```{r}
#| eval: false
here("data-raw/nurses-stress/stress/6B/6B_1587569373/EDA.csv.gz") %>%
  read_csv(
    show_col_types = FALSE,
    name_repair = to_snake_case,
    n_max = 100
  )
```

## Create function

Add values: 

```{r}
#' Add two numbers together
#'
#' @param num1 a number here
#' @param num2 a number here
#'
#' @returns Returns the sum of 2 numbers
#'
#'
add_numbers <- function(num1, num2) {
  added <- num1 + num2
  return(added)
}
```


```{r}
#| eval: false
# Outputs only 100 rows
here("data-raw/nurses-stress/stress/5C/5C_1586886626/HR.csv.gz") %>%
  read()

# Outputs only 1000 rows
here("data-raw/nurses-stress/stress/5C/5C_1586886712/HR.csv.gz") %>%
  read(max_rows = 1000)

# Outputs all rows (`Inf` means infinity)
here("data-raw/nurses-stress/stress/5C/5C_1586886712/HR.csv.gz") %>%
  read(max_rows = Inf)
```



#Using map
```{r usingmap}
#| eval: false
#| include: false

#' Read all data
#'
#' @param filename
#'
#' @returns readall
#'
#'
read_all <- function(filename) {
  files <- here("data-raw/nurses-stress/") %>%
    fs::dir_ls(regexp = "HR.csv.gz", recurse = TRUE)

  data <- files %>%
    purrr::map(read) %>%
    purrr::list_rbind(names_to = "file_path_id")
  return(data)
}

read_all("HR.csv.gz")
```

##Inspecting data

```{r}
hr_data <- read_all("HR.csv.gz")

survey_data <- here("data-raw/nurses-stress/survey-results.csv.gz") |>
  read()
hr_data
survey_data
```


```{r}
#| eval: false
#| include: false
hr_data %>%
  mutate(
    id = str_extract(
      `file_path_id`,
      pattern = "/stress/[:alnum:]{2}/"
    ) %>%
      str_remove("/stress/") %>%
      str_remove("/"),
    .before = `file_path_id`
  )
```
```{r}
#| eval: false
#| include: false
hr_data %>%
  mutate(
    id = str_extract(
      `file_path_id)`,
      pattern = "/stress/[:alnum:]{2}/"
    ) %>%
      str_remove("/stress/") %>%
      str_remove("/"),
    .before = `file_path_id)`
  ) %>%
  select(-`file_path_id)`)
```

##Function to get ID: 

```{r}
#| eval: false
#| include: false
#' Get participant id
#'
#' @param ID
#'
#' @returns ID
#' @export
#'
#' @examples
get_participant_id <- function(data) {
  data_with_id <- data %>%
    dplyr::mutate(
      id = stringr::str_extract(
        file_path_id,
        "/stress/[:alnum:]{2}/"
      ) %>%
        stringr::str_remove("/stress/") %>%
        stringr::str_remove("/"),
      .before = file_path_id
    ) %>%
    dplyr::select(-file_path_id)
  return(data_with_id)
}
```

## Working with across: 

```{r}
hr_data <- read_all("HR.csv.gz") %>%
  get_participant_id()
```
```{r}
hr_data %>%
  summarise(across(hr, mean))
```

```{r}
hr_data %>%
  summarise(across(hr, list(
    mean = mean,
    median = median, sd = sd
  )))
```
```{r}
hr_data %>%
  summarise(across(where(is.numeric), list(
    mean = mean,
    median = median, sd = sd
  )))
```
##Working with dates: 


```{r}
hr_data %>%
  mutate(datetime = round_date(collection_datetime, unit = "minute"), .before = collection_datetime)
```


## Summarising by groups: 

```{r}
hr_data %>%
  mutate(
    collection_datetime = round_date(
      collection_datetime,
      unit = "minute"
    )
  ) %>%
  summarise(
    across(where(is.numeric), list(mean = mean, sd = sd, median = median)),
    .by = c(id, collection_datetime)
  )
```


## Exercise: 

```{r}
#| eval: false
#| include: false
#' Summarizing data
#'
#' @param data 
#'
#' @returns

summarise_by_datetime <- function (data) {
  summarised_data <- data %>% 
  dplyr::mutate(
    collection_datetime = lubridate::round_date(
      collection_datetime,
      unit = "minute"
    )
  ) %>%
  dplyr::summarise(
    dplyr::across(tidyselect::where(is.numeric), base::list(mean = mean, sd = sd, median = median)),
    .by = c(id, collection_datetime))
  return(summarised_data)
    
}



```

##Pivot longer: 

```{r}
survey_data <- here("data-raw/nurses-stress/survey-results.csv.gz") %>% 
  read()
survey_data
```

```{r}
survey_data %>% 
  mutate(date = as_date(date))
```

```{r}
survey_tidy <- survey_data |>
  mutate(
    date = mdy(date),
    start_datetime = as_datetime(paste(date, start_time)),
    end_datetime = as_datetime(paste(date, end_time)),
    datetime_id = start_datetime,
    .before = start_time
  ) |>
  select(-c(date, start_time, end_time, duration))
```


```{r}
survey_data 
```

